version: "3.9"
services:
  app:
    build:
      context: .
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
        VITE_MICROSOFT_CLIENT_ID: ${VITE_MICROSOFT_CLIENT_ID}
        VITE_MICROSOFT_TENANT_ID: ${VITE_MICROSOFT_TENANT_ID}
        VITE_REDIRECT_URI: ${VITE_REDIRECT_URI}
    container_name: app
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
      - ./frontend/.env
    volumes:
      - ./backend/uploads/pdfs:/app/backend/uploads/pdfs
    restart: unless-stopped
