version: "3.9"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads/pdfs:/app/uploads/pdfs
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
        VITE_MICROSOFT_CLIENT_ID: ${VITE_MICROSOFT_CLIENT_ID}
        VITE_MICROSOFT_TENANT_ID: ${VITE_MICROSOFT_TENANT_ID}
        VITE_REDIRECT_URI: ${VITE_REDIRECT_URI}
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
